package Presentacion;

import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logicaBD.DBOrder;

public class FrmOrder extends javax.swing.JInternalFrame {

    public FrmOrder() throws Exception {
        initComponents();
        this.setSize(647, 470);
        loadOrder();
    }
    
    
    DBOrder dBOrder = new DBOrder();
    
    DefaultTableModel model = new DefaultTableModel();

    void loadOrder() throws Exception {
        DBOrder dBOrder = new DBOrder();
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        model.addColumn("Orden");
        model.addColumn("Fecha");
        model.addColumn("Estado");

        ArrayList<Object[]> data = new ArrayList<>();

        data = dBOrder.fillTableOrder();
        for (int i = 0; i < data.size(); i++) {

            model.addRow(data.get(i));

        }
        tblOrder.setModel(model);

        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnDispatch = new javax.swing.JButton();

        setClosable(true);
        setTitle("Plato");
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Platos"));
        jPanel2.setLayout(null);

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Categoriía", "Nombre", "Descripción", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblOrder);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 92, 580, 280);

        txtSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.add(txtSearch);
        txtSearch.setBounds(80, 40, 520, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Buscar:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 50, 60, 17);

        btnDispatch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDispatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/files/Proveedores.png"))); // NOI18N
        btnDispatch.setText("Despachar Pedido");
        jPanel2.add(btnDispatch);
        btnDispatch.setBounds(400, 380, 200, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 10, 610, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDispatch;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
