package Presentacion;

import javax.swing.BorderFactory;
import javax.swing.JPanel;


public class FrmPhotoVisor extends javax.swing.JInternalFrame {


    public FrmPhotoVisor() {
        initComponents();
        this.setSize(361, 348);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDish = new javax.swing.JPanel();
        lblPhoto = new javax.swing.JLabel();
        lblDishName = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Foto del Plato");
        getContentPane().setLayout(null);

        pnlDish.setBackground(new java.awt.Color(204, 204, 255));
        pnlDish.setBorder(javax.swing.BorderFactory.createTitledBorder("Plato"));
        pnlDish.setLayout(null);
        pnlDish.add(lblPhoto);
        lblPhoto.setBounds(10, 10, 300, 230);

        lblDishName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDishName.setForeground(new java.awt.Color(51, 51, 255));
        lblDishName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDishName.setText("Dish Name");
        pnlDish.add(lblDishName);
        lblDishName.setBounds(10, 250, 310, 40);

        getContentPane().add(pnlDish);
        pnlDish.setBounds(10, 11, 320, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel lblDishName;
    public static javax.swing.JLabel lblPhoto;
    public static javax.swing.JPanel pnlDish;
    // End of variables declaration//GEN-END:variables
}
